{% set version = "1.3.0" %}
{% set name = "CytoTree" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: b80929abc08c1dda9dce42f088df8f3a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BiocGenerics, knitr, RColorBrewer, rmarkdown, testthat, BiocStyle
requirements:
  host:
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocneighbors >=1.12.0,<1.13.0'
    - 'bioconductor-destiny >=3.8.0,<3.9.0'
    - 'bioconductor-flowcore >=2.6.0,<2.7.0'
    - 'bioconductor-flowsom >=2.2.0,<2.3.0'
    - 'bioconductor-flowutils >=1.58.0,<1.59.0'
    - 'bioconductor-limma >=3.50.0,<3.51.0'
    - 'bioconductor-sva >=3.42.0,<3.43.0'
    - r-base
    - r-cluster
    - r-ggplot2
    - r-gmodels
    - r-igraph
    - r-matrix
    - r-matrixstats
    - r-mclust
    - r-pheatmap
    - r-prettydoc
    - 'r-rann >=2.5'
    - 'r-rcpp >=0.12.0'
    - r-rtsne
    - r-scatterpie
    - r-scatterplot3d
    - r-stringr
    - r-umap
    - libblas
    - liblapack
  run:
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocneighbors >=1.12.0,<1.13.0'
    - 'bioconductor-destiny >=3.8.0,<3.9.0'
    - 'bioconductor-flowcore >=2.6.0,<2.7.0'
    - 'bioconductor-flowsom >=2.2.0,<2.3.0'
    - 'bioconductor-flowutils >=1.58.0,<1.59.0'
    - 'bioconductor-limma >=3.50.0,<3.51.0'
    - 'bioconductor-sva >=3.42.0,<3.43.0'
    - r-base
    - r-cluster
    - r-ggplot2
    - r-gmodels
    - r-igraph
    - r-matrix
    - r-matrixstats
    - r-mclust
    - r-pheatmap
    - r-prettydoc
    - 'r-rann >=2.5'
    - 'r-rcpp >=0.12.0'
    - r-rtsne
    - r-scatterpie
    - r-scatterplot3d
    - r-stringr
    - r-umap
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'A Toolkit for Flow And Mass Cytometry Data'
  description: 'A trajectory inference toolkit for flow and mass cytometry data. CytoTree is a valuable tool to build a tree-shaped trajectory using flow and mass cytometry data. The application of CytoTree ranges from clustering and dimensionality reduction to trajectory reconstruction and pseudotime estimation. It offers complete analyzing workflow for flow and mass cytometry data.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

