{% set name = "masurca" %}
{% set version = "4.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/alekseyzimin/masurca/releases/download/v{{ version }}/MaSuRCA-{{ version }}.tar.gz
  sha256: 2b04193fd1aad589fa1d57b5d9950f3b9de7e78e57c45513c08ab344415fa32e

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - yaggo
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - zlib
    - bzip2
    - boost-cpp
    - perl 
  run:
    - zlib
    - boost-cpp
    - perl
    - grep

test:
  commands:
    - masurca --help

about:
  home: http://masurca.blogspot.co.uk/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: |
    MaSuRCA (Maryland Super-Read Celera Assembler) genome assembly software.
    MaSuRCA requires Illumina data, and supports third-generation PacBio/Nanopore
    MinION reads for hybrid assembly.

extra:
  identifiers:
    - biotools:masurca
    - doi:10.1093/bioinformatics/btt476
