{% set version = "2.12.0" %}
{% set name = "RnBeads" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: bbd19b2cafa7ecb507be66ec1c49c4ee
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: Category, GOstats, Gviz, IlluminaHumanMethylation450kmanifest, RPMM, RefFreeEWAS, RnBeads.hg19, RnBeads.mm9, XML, annotate, biomaRt, foreach, doParallel, ggbio, isva, mclust, mgcv, minfi, nlme, org.Hs.eg.db, org.Mm.eg.db, org.Rn.eg.db, quadprog, rtracklayer, qvalue, sva, wateRmelon, wordcloud, qvalue, argparse, glmnet, GLAD, IlluminaHumanMethylation450kanno.ilmn12.hg19, scales, missMethyl, impute, shiny, shinyjs, plotrix, hexbin, RUnit, MethylSeekR, sesame
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-genomicranges >=1.46.0,<1.47.0'
    - 'bioconductor-illuminaio >=0.36.0,<0.37.0'
    - 'bioconductor-iranges >=2.28.0,<2.29.0'
    - 'bioconductor-limma >=3.50.0,<3.51.0'
    - 'bioconductor-methylumi >=2.39.0,<2.40.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - r-base
    - r-cluster
    - r-ff
    - r-fields
    - 'r-ggplot2 >=0.9.2'
    - r-gplots
    - r-gridextra
    - r-mass
    - r-matrixstats
    - r-plyr
  run:
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-genomicranges >=1.46.0,<1.47.0'
    - 'bioconductor-illuminaio >=0.36.0,<0.37.0'
    - 'bioconductor-iranges >=2.28.0,<2.29.0'
    - 'bioconductor-limma >=3.50.0,<3.51.0'
    - 'bioconductor-methylumi >=2.39.0,<2.40.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - r-base
    - r-cluster
    - r-ff
    - r-fields
    - 'r-ggplot2 >=0.9.2'
    - r-gplots
    - r-gridextra
    - r-mass
    - r-matrixstats
    - r-plyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: RnBeads
  description: 'RnBeads facilitates comprehensive analysis of various types of DNA methylation data at the genome scale.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  parent_recipe:
    name: bioconductor-rnbeads
    path: recipes/bioconductor-rnbeads
    version: 1.12.1

