{% set version = "0.4.0" %}

package:
  name: fade
  version: '{{ version }}'

source:
  url: https://github.com/blachlylab/fade/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2cfacdd1d6818af526bb6057960c7c4acae72af8c24e31837a4fb22c0259c2c4


build:
  number: 0
  # binary_relocation: False # [linux]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - htslib
    - wget
  run:
    - htslib

test:
  commands:
    - fade
  
about:
  home: https://github.com/blachlylab/fade
  license: MIT
  summary: "fade is a D program that provides fast identification and removal of enzymatic fragmentation artifacts."

extra:
  identifiers:
    - doi:10.1093/nargab/lqaa070


