{% set version = "2.0.0" %}
{% set name = "greengenes13.5MgDb" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: c06d8d5b702636bb5fb3e6229869578c
build:
  number: 8
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - r-base
    - 'r-metagenomefeatures >=1.9.9'
  run:
    - r-base
    - 'r-metagenomefeatures >=1.9.9'
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Greengenes 13.5 16S rRNA Database Annotation Data'
  description: 'Metagenome annotation package with for the Greengenes 16S rRNA Database version 13.5. Contains a MgDb-class object, defined in the metagenomeFeatures package.'

