{% set version = "1.6.0" %}
{% set name = "MicrobiotaProcess" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 85d9652f00224bd576893c012fa0d56c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: rmarkdown, prettydoc, testthat, knitr, nlme, phangorn, picante, plyr, DECIPHER, randomForest, biomformat, scales, yaml, withr, S4Vectors, purrr, seqmagick, glue, corrr, ggupset, ggVennDiagram, gghalves, ggalluvial, forcats, pillar, cli, phyloseq, aplot, ggnewscale, ggside, ggtreeExtra
requirements:
  host:
    - 'bioconductor-biostrings >=2.62.0,<2.63.0'
    - 'bioconductor-ggtree >=3.2.0,<3.3.0'
    - 'bioconductor-summarizedexperiment >=1.24.0,<1.25.0'
    - 'bioconductor-treeio >=1.18.0,<1.19.0'
    - bioconductor-phyloseq
    - r-ggnewscale
    - r-ape
    - r-base
    - r-coin
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-ggsignif
    - r-ggstar
    - r-magrittr
    - r-mass
    - r-patchwork
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - 'r-tidytree >=0.3.5'
    - r-vegan
    - r-zoo
  run:
    - 'bioconductor-biostrings >=2.62.0,<2.63.0'
    - 'bioconductor-ggtree >=3.2.0,<3.3.0'
    - 'bioconductor-summarizedexperiment >=1.24.0,<1.25.0'
    - 'bioconductor-treeio >=1.18.0,<1.19.0'
    - bioconductor-phyloseq
    - r-ggnewscale
    - r-ape
    - r-base
    - r-coin
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-ggsignif
    - r-ggstar
    - r-magrittr
    - r-mass
    - r-patchwork
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - 'r-tidytree >=0.3.5'
    - r-vegan
    - r-zoo
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 3.0)'
  summary: 'an R package for analysis, visualization and biomarker discovery of microbiome'
  description: 'MicrobiotaProcess is an R package for analysis, visualization and biomarker discovery of microbial datasets. It introduces MPSE class, this make it more interoperable with the existing computing ecosystem. Moreover, it introduces a tidy microbiome data structure paradigm and analysis grammar. It provides a wide variety of microbiome analsys procedures under the unified and common framework (tidy-like framework).'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

