{% set name = "run-dbcan" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/run_dbcan-{{ version }}.tar.gz
  sha256: 1356f9ec681c33599c701ffbf32b52e22bbcc523129b7ca116fb443531ef241d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - natsort
    - pip
    - python
    - setuptools
    - setuptools_scm_git_archive
  run:
    - natsort
    - python
    - fraggenescan
    - prodigal
    - diamond
    - hmmer

test:
  commands:
    - run_dbcan.py --help

about:
  home: "https://github.com/linnabrown/run_dbcan"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE 
  summary: "Standalone version of dbCAN annotation tool for automated CAZyme annotation"

extra:
  recipe-maintainers:
    - lecorguille
