{% set version = "1.9.0" %}
{% set name = "phemd" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: bb5427af1e6b4c2c71a4023c3d5ac16e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr
requirements:
  host:
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-destiny >=3.8.0,<3.9.0'
    - 'bioconductor-monocle >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - 'bioconductor-singlecellexperiment >=1.16.0,<1.17.0'
    - 'bioconductor-summarizedexperiment >=1.24.0,<1.25.0'
    - r-base
    - r-cluster
    - r-cowplot
    - r-ggplot2
    - r-igraph
    - r-maptree
    - r-phater
    - r-pheatmap
    - r-pracma
    - r-rann
    - r-rcolorbrewer
    - r-reticulate
    - r-rtsne
    - r-scatterplot3d
    - r-seurat
    - r-transport
    - r-vgam
  run:
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-destiny >=3.8.0,<3.9.0'
    - 'bioconductor-monocle >=2.22.0,<2.23.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - 'bioconductor-singlecellexperiment >=1.16.0,<1.17.0'
    - 'bioconductor-summarizedexperiment >=1.24.0,<1.25.0'
    - r-base
    - r-cluster
    - r-cowplot
    - r-ggplot2
    - r-igraph
    - r-maptree
    - r-phater
    - r-pheatmap
    - r-pracma
    - r-rann
    - r-rcolorbrewer
    - r-reticulate
    - r-rtsne
    - r-scatterplot3d
    - r-seurat
    - r-transport
    - r-vgam
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Phenotypic EMD for comparison of single-cell samples'
  description: 'Package for comparing and generating a low-dimensional embedding of multiple single-cell samples.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

