{% set version = "2.39.0" %}
{% set name = "methylumi" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  md5: feaae07e28ca7764f57222391c6590a3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: lumi, lattice, limma, xtable, SQN, MASS, matrixStats, parallel, rtracklayer, Biostrings, methyAnalysis, TCGAMethylation450k, IlluminaHumanMethylation450kanno.ilmn12.hg19, FDb.InfiniumMethylation.hg18 (>= 2.2.0), Homo.sapiens, knitr
requirements:
  host:
    - 'bioconductor-annotate >=1.72.0,<1.73.0'
    - 'bioconductor-annotationdbi >=1.56.0,<1.57.0'
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-fdb.infiniummethylation.hg19 >=2.2.0,<2.3.0'
    - 'bioconductor-genefilter >=1.76.0,<1.77.0'
    - 'bioconductor-genomeinfodb >=1.30.0,<1.31.0'
    - 'bioconductor-genomicranges >=1.46.0,<1.47.0'
    - 'bioconductor-illuminaio >=0.36.0,<0.37.0'
    - 'bioconductor-iranges >=2.28.0,<2.29.0'
    - 'bioconductor-minfi >=1.40.0,<1.41.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - 'bioconductor-summarizedexperiment >=1.24.0,<1.25.0'
    - r-base
    - r-ggplot2
    - r-lattice
    - r-matrixstats
    - r-reshape2
    - r-scales
  run:
    - 'bioconductor-annotate >=1.72.0,<1.73.0'
    - 'bioconductor-annotationdbi >=1.56.0,<1.57.0'
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-fdb.infiniummethylation.hg19 >=2.2.0,<2.3.0'
    - 'bioconductor-genefilter >=1.76.0,<1.77.0'
    - 'bioconductor-genomeinfodb >=1.30.0,<1.31.0'
    - 'bioconductor-genomicranges >=1.46.0,<1.47.0'
    - 'bioconductor-illuminaio >=0.36.0,<0.37.0'
    - 'bioconductor-iranges >=2.28.0,<2.29.0'
    - 'bioconductor-minfi >=1.40.0,<1.41.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - 'bioconductor-summarizedexperiment >=1.24.0,<1.25.0'
    - r-base
    - r-ggplot2
    - r-lattice
    - r-matrixstats
    - r-reshape2
    - r-scales
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Handle Illumina methylation data'
  description: 'This package provides classes for holding and manipulating Illumina methylation data.  Based on eSet, it can contain MIAME information, sample information, feature information, and multiple matrices of data.  An "intelligent" import function, methylumiR can read the Illumina text files and create a MethyLumiSet. methylumIDAT can directly read raw IDAT files from HumanMethylation27 and HumanMethylation450 microarrays. Normalization, background correction, and quality control features for GoldenGate, Infinium, and Infinium HD arrays are also included.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
extra:
  identifiers:
    - biotools:methylumi
    - doi:10.1186/1471-2164-14-293
  parent_recipe:
    name: bioconductor-methylumi
    path: recipes/bioconductor-methylumi
    version: 2.26.0

